ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

STATEOS_ARCH     := stm8
STATEOS_DEVICE   := stm8s
STATEOS_COMPILER := csmc

#----------------------------------------------------------#
include $(COMMON)/make/stm8discovery/makefile.csmc
#----------------------------------------------------------#
