ifndef STATEOS_NASA_INCLUDE_GUARD
       STATEOS_NASA_INCLUDE_GUARD:=ON

ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

INCS += $(COMMON)/stateos/nasa/bsp/shared/inc
INCS += $(COMMON)/stateos/nasa/os/inc
INCS += $(COMMON)/stateos/nasa/os/shared/inc
INCS += $(COMMON)/stateos/nasa/os/stateos/inc

SRCS += $(COMMON)/stateos/nasa/bsp/shared/src/bsp_default_app_run.c
SRCS += $(COMMON)/stateos/nasa/bsp/shared/src/bsp_default_app_startup.c
SRCS += $(COMMON)/stateos/nasa/bsp/shared/src/bsp_default_symtab.c
SRCS += $(COMMON)/stateos/nasa/bsp/shared/src/osapi-bsp.c
SRCS += $(COMMON)/stateos/nasa/bsp/stateos/src/bsp_console.c
SRCS += $(COMMON)/stateos/nasa/bsp/stateos/src/bsp_start.c
SRCS += $(COMMON)/stateos/nasa/os/portable/os-impl-console-bsp.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-binsem.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-clock.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-common.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-countsem.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-debug.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-dir.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-errors.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-file.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-filesys.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-heap.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-idmap.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-module.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-mutex.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-network.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-printf.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-queue.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-select.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-shell.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-sockets.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-task.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-time.c
SRCS += $(COMMON)/stateos/nasa/os/shared/src/osapi-timebase.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-binsem.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-clock.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-common.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-console.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-countsem.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-errors.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-idmap.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-mutex.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-dirs.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-files.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-filesys.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-heap.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-io.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-loader.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-network.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-select.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-shell.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-sockets.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-no-symtab.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-queues.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-tasks.c
SRCS += $(COMMON)/stateos/nasa/os/stateos/src/os-impl-timebase.c

include $(COMMON)/stateos/makefile

endif
