ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f746g-disco/makefile.clang
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f7

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
