ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.clang
#----------------------------------------------------------#

CMSISOS_TARGET   := armv7m
CMSISOS_COMPILER := GCC

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
