ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f0discovery/makefile.armcc
#----------------------------------------------------------#

CMSISOS_COMPILER := ARM
CMSISOS_PORTFILE := irq_cm0.s

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
