ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f0discovery/makefile.iarcc
#----------------------------------------------------------#

CMSISOS_TARGET   := cm0
CMSISOS_COMPILER := IAR

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
