ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.iarcc
#----------------------------------------------------------#

CMSISOS_TARGET   := armv7m
CMSISOS_COMPILER := IAR

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
