ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.clang
#----------------------------------------------------------#

CMSISOS_TARGET   := cm4f
CMSISOS_COMPILER := GCC

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
