ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/attiny817xmini/makefile.gcc
#----------------------------------------------------------#

STATEOS_ARCH     := avr
STATEOS_DEVICE   := attiny817
STATEOS_COMPILER := gcc

#----------------------------------------------------------#
include $(COMMON)/stateos/nano/makefile
#----------------------------------------------------------#
