ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

DEMOS_ARCH   := x86
DEMOS_DEVICE := x86

#----------------------------------------------------------#
include $(COMMON)/make/pc/makefile.gcc
#----------------------------------------------------------#
