ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

INTROS_ARCH     := stm8
INTROS_DEVICE   := stm8s
INTROS_COMPILER := iarc

#----------------------------------------------------------#
include $(COMMON)/make/stm8discovery/makefile.iarc
#----------------------------------------------------------#
