#----------------------------------------------------------#

TARGET_PLATFORM := stm32f746g-disco
TARGET_CHIP     := stm32f746ng
TARGET_DEVICE   := stm32f7
TARGET_CORE     := cortex-m7
TARGET_ARCH     := cortexm
TARGET_COMPILER := armcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .lib

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F746xx

#----------------------------------------------------------#

COMMON_F = --fpu=$(if $(filter qemu,$(MAKECMDGOALS)),softvfp,fpv5-sp)

#----------------------------------------------------------#
