#----------------------------------------------------------#

TARGET_PLATFORM := stm32f746g-disco
TARGET_CHIP     := stm32f746ng
TARGET_DEVICE   := stm32f7
TARGET_CORE     := cortex-m7
TARGET_ARCH     := cortexm
TARGET_COMPILER := csmcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .cxm

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F746xx

#----------------------------------------------------------#

LIBS   += $(if $(filter qemu,$(MAKECMDGOALS)),libflc.cxm,libfpulc.cxm)
C_FLAGS = $(if $(filter qemu,$(MAKECMDGOALS)),,+fpu)

#----------------------------------------------------------#
