#----------------------------------------------------------#

TARGET_PLATFORM := stm32f0discovery
TARGET_CHIP     := stm32f051r8
TARGET_DEVICE   := stm32f0
TARGET_CORE     := cortex-m0
TARGET_ARCH     := cortexm
TARGET_COMPILER := csmcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .cx0

#----------------------------------------------------------#

QEMU_BOARD := STM32F0-Discovery
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F051x8

#----------------------------------------------------------#
