ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

DEMOS_ARCH     := stm8
DEMOS_DEVICE   := stm8s

#----------------------------------------------------------#
include $(COMMON)/make/stm8discovery/makefile.iarc
#----------------------------------------------------------#
