ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

INTROS_ARCH     := x86
INTROS_DEVICE   := x86
INTROS_COMPILER := gcc

#----------------------------------------------------------#
include $(COMMON)/make/pc/makefile.gcc
#----------------------------------------------------------#
