ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/attiny817xmini/makefile.gcc
#----------------------------------------------------------#

INTROS_ARCH     := avr
INTROS_DEVICE   := attiny817
INTROS_COMPILER := gcc

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
