ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

SRCS += $(COMMON)/startup/$(TARGET_CHIP)/$(TARGET_COMPILER)/startup.s

SCRIPT += $(COMMON)/startup/$(TARGET_CHIP)/$(TARGET_COMPILER)/script.sct
