ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/32f746gdiscovery/makefile.clang
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f7
INTROS_COMPILER := clang

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
