#----------------------------------------------------------#

TARGET_PLATFORM := 32f746gdiscovery
TARGET_CHIP     := stm32f746ng
TARGET_DEVICE   := stm32f7
TARGET_CORE     := cortex-m7
TARGET_ARCH     := cortexm
TARGET_COMPILER := clang

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .lib

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := stm32f746g-disco

#----------------------------------------------------------#

DEFS += STM32F746xx

#----------------------------------------------------------#

COMMON_F = -mfpu=fpv5-sp-d16 -ffast-math -mfloat-abi=$(if $(filter qemu,$(MAKECMDGOALS)),soft,hard)

#----------------------------------------------------------#
