ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.iarcc
#----------------------------------------------------------#

CMSISOS_COMPILER := IAR
CMSISOS_PORTFILE := irq_cm4f.s

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
