ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32l4discovery/makefile.csmcc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32l4
INTROS_COMPILER := csmcc

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
