ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32l4discovery/makefile.armcc
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32l4

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
