ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/32f746gdiscovery/makefile.clang
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f7

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
