ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f0discovery/makefile.armcc
#----------------------------------------------------------#

CMSISOS_TARGET   := armv6m
CMSISOS_COMPILER := ARM

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
