#----------------------------------------------------------#

TARGET_PLATFORM := stm32l4discovery
TARGET_CHIP     := stm32l476vg
TARGET_DEVICE   := stm32l4
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := gnucc

#----------------------------------------------------------#

LIBRARY_PREFIX  := lib
LIBRARY_SUFFIX  := .a

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32L476xx

#----------------------------------------------------------#

COMMON_F = -mfpu=fpv4-sp-d16 -ffast-math -mfloat-abi=$(if $(filter qemu,$(MAKECMDGOALS)),soft,hard)

#----------------------------------------------------------#
