#----------------------------------------------------------#

TARGET_PLATFORM := stm32l4discovery
TARGET_CHIP     := stm32l476vg
TARGET_DEVICE   := stm32l4
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := csmcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .cxm

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32L476xx

#----------------------------------------------------------#

LIBS   += $(if $(filter qemu,$(MAKECMDGOALS)),libflc.cxm,libfpulc.cxm)
C_FLAGS = $(if $(filter qemu,$(MAKECMDGOALS)),,+fpu)

#----------------------------------------------------------#
