ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm8sdiscovery/makefile.sdcc
#----------------------------------------------------------#

DEMOS_ARCH     := stm8
DEMOS_DEVICE   := stm8s

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
