ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.clang
#----------------------------------------------------------#

CMSISOS_COMPILER := GCC
CMSISOS_PORTFILE := irq_cm4f.S

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
