ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.gnucc
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f4

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
