ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f4

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.armcc
#----------------------------------------------------------#
