ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/st7custom/makefile.csmc
#----------------------------------------------------------#

DEMOS_ARCH     := st7
DEMOS_DEVICE   := st7

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
