ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f4
INTROS_COMPILER := armcc

#----------------------------------------------------------#
include $(COMMON)/make/stm32f4discovery/makefile.armcc
#----------------------------------------------------------#
