ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.gnucc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32l1
INTROS_COMPILER := gnucc

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
