ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32l1
INTROS_COMPILER := csmcc

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.csmcc
#----------------------------------------------------------#
