ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.gnucc
#----------------------------------------------------------#

CMSISOS_COMPILER := GCC
CMSISOS_PORTFILE := irq_cm3.S

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
