ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.iarcc
#----------------------------------------------------------#

CMSISOS_COMPILER := IAR
CMSISOS_PORTFILE := irq_cm3.s

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
