ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.iarcc
#----------------------------------------------------------#

CMSISOS_TARGET   := cm3
CMSISOS_COMPILER := IAR

#----------------------------------------------------------#
include $(COMMON)/cmsis/os/makefile
#----------------------------------------------------------#
