ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/32f746gdiscovery/makefile.armcc
#----------------------------------------------------------#

STATEOS_ARCH     := cortexm
STATEOS_DEVICE   := stm32f7
STATEOS_COMPILER := armcc

#----------------------------------------------------------#
include $(COMMON)/stateos/makefile
#----------------------------------------------------------#
