ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f0discovery/makefile.csmcc
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f0

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
