ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.clang
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f3
INTROS_COMPILER := clang

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
