ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.gnucc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f3
INTROS_COMPILER := gnucc

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
