ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.armcc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f3
INTROS_COMPILER := armcc

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
