ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.iarcc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f3
INTROS_COMPILER := iarcc

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
