ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.iarcc
#----------------------------------------------------------#

STATEOS_ARCH     := cortexm
STATEOS_DEVICE   := stm32l1
STATEOS_COMPILER := iarcc

#----------------------------------------------------------#
include $(COMMON)/stateos/makefile
#----------------------------------------------------------#
