ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

STATEOS_ARCH     := cortexm
STATEOS_DEVICE   := stm32l1
STATEOS_COMPILER := csmcc

#----------------------------------------------------------#
include $(COMMON)/make/stm32ldiscovery/makefile.csmcc
#----------------------------------------------------------#
