ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f746g-disco/makefile.armcc
#----------------------------------------------------------#

INTROS_ARCH     := cortexm
INTROS_DEVICE   := stm32f7
INTROS_COMPILER := armcc

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
