#----------------------------------------------------------#

TARGET_PLATFORM := stm32f3discovery
TARGET_CHIP     := stm32f303vc
TARGET_DEVICE   := stm32f3
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := csmcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .cxm

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F303xC

#----------------------------------------------------------#

LIBS   += $(if $(filter qemu,$(MAKECMDGOALS)),libflc.cxm,libfpulc.cxm)
C_FLAGS = $(if $(filter qemu,$(MAKECMDGOALS)),,+fpu)

#----------------------------------------------------------#
