#----------------------------------------------------------#

TARGET_PLATFORM := stm32f3discovery
TARGET_CHIP     := stm32f303vc
TARGET_DEVICE   := stm32f3
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := iarcc

#----------------------------------------------------------#

LIBRARY_PREFIX  := lib
LIBRARY_SUFFIX  := .a

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F303xC

#----------------------------------------------------------#

CORE_F = --fpu $(if $(filter qemu,$(MAKECMDGOALS)),none,vfpv4_sp)

#----------------------------------------------------------#
