#----------------------------------------------------------#

TARGET_PLATFORM := stm32f3discovery
TARGET_CHIP     := stm32f303vc
TARGET_DEVICE   := stm32f3
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := armcc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .lib

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F303xC

#----------------------------------------------------------#

COMMON_F = --fpu=$(if $(filter qemu,$(MAKECMDGOALS)),softvfp,fpv4-sp)

#----------------------------------------------------------#
