ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm8sdiscovery/makefile.sdcc
#----------------------------------------------------------#

INTROS_ARCH     := stm8
INTROS_DEVICE   := stm8s
INTROS_COMPILER := sdcc

#----------------------------------------------------------#
include $(COMMON)/intros/makefile
#----------------------------------------------------------#
