ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

LIBS += $(COMMON)/startup/$(TARGET_CHIP)/$(TARGET_COMPILER)/vectors.cx0

SCRIPT += $(COMMON)/startup/$(TARGET_CHIP)/$(TARGET_COMPILER)/script.lkf
