#----------------------------------------------------------#

TARGET_PLATFORM := attiny817xmini
TARGET_CHIP     := attiny817
TARGET_DEVICE   := attiny817
TARGET_CORE     := avrxmega3
TARGET_ARCH     := avr
TARGET_COMPILER := gcc

#----------------------------------------------------------#

LIBRARY_PREFIX  := lib
LIBRARY_SUFFIX  := .a

#----------------------------------------------------------#

DEFS += F_CPU=20000000

#----------------------------------------------------------#
