ifndef DEVICE_PLATFORM_INCLUDE_GUARD
       DEVICE_PLATFORM_INCLUDE_GUARD:=ON

ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

INCS += $(COMMON)/device/$(TARGET_PLATFORM)

SRCS += $(COMMON)/device/$(TARGET_PLATFORM)/stm32l_discovery_lcd.c

endif
