ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#

STATEOS_ARCH     := cortexm
STATEOS_DEVICE   := stm32f0
STATEOS_COMPILER := clang

#----------------------------------------------------------#
include $(COMMON)/make/stm32f0discovery/makefile.clang
#----------------------------------------------------------#
