#----------------------------------------------------------#

TARGET_PLATFORM := st7custom
TARGET_CHIP     := st72334n4
TARGET_DEVICE   := st7
TARGET_CORE     := st7
TARGET_ARCH     := st7
TARGET_COMPILER := csmc

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .st7

#----------------------------------------------------------#

DEFS += ST72334

#----------------------------------------------------------#
