ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/stm32f3discovery/makefile.armcc
#----------------------------------------------------------#

DEMOS_ARCH     := cortexm
DEMOS_DEVICE   := stm32f3

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
