ifndef COMMON
$(error Please define COMMON path before including any common package)
endif

#----------------------------------------------------------#
include $(COMMON)/make/attiny817xmini/makefile.gcc
#----------------------------------------------------------#

DEMOS_ARCH   := avr8
DEMOS_DEVICE := attiny817

#----------------------------------------------------------#
include $(COMMON)/demos/makefile
#----------------------------------------------------------#
