#----------------------------------------------------------#

TARGET_PLATFORM := stm32ldiscovery
TARGET_CHIP     := stm32l152rb
TARGET_DEVICE   := stm32l1
TARGET_CORE     := cortex-m3
TARGET_ARCH     := cortexm
TARGET_COMPILER := clang

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .lib

#----------------------------------------------------------#

QEMU_BOARD :=
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32L152xB

#----------------------------------------------------------#
