#----------------------------------------------------------#

TARGET_PLATFORM := stm32f4discovery
TARGET_CHIP     := stm32f407vg
TARGET_DEVICE   := stm32f4
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := clang

#----------------------------------------------------------#

LIBRARY_PREFIX  :=
LIBRARY_SUFFIX  := .lib

#----------------------------------------------------------#

QEMU_BOARD := STM32F4-Discovery
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F407xx

#----------------------------------------------------------#

COMMON_F = -mfpu=fpv4-sp-d16 -ffast-math -mfloat-abi=$(if $(filter qemu,$(MAKECMDGOALS)),soft,hard)

#----------------------------------------------------------#
