#----------------------------------------------------------#

TARGET_PLATFORM := stm32f4discovery
TARGET_CHIP     := stm32f407vg
TARGET_DEVICE   := stm32f4
TARGET_CORE     := cortex-m4
TARGET_ARCH     := cortexm
TARGET_COMPILER := iarcc

#----------------------------------------------------------#

LIBRARY_PREFIX  := lib
LIBRARY_SUFFIX  := .a

#----------------------------------------------------------#

QEMU_BOARD := STM32F4-Discovery
OOCD_BOARD := $(TARGET_PLATFORM)

#----------------------------------------------------------#

DEFS += STM32F407xx

#----------------------------------------------------------#

CORE_F = --fpu $(if $(filter qemu,$(MAKECMDGOALS)),none,vfpv4_sp)

#----------------------------------------------------------#
